/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
    subscription: NexusGenRootTypes['Subscription']; // Subscription!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // root type
    _id: string; // String!
    contextObjectKey?: string | null; // String
    indexError?: string | null; // String
    indexStatus?: string | null; // String
    isSubscribed?: boolean | null; // Boolean
    jobId: string; // String!
    title: string; // String!
    userId: string; // String!
  }
  BookIndexStatus: { // root type
    contextObjectKey?: string | null; // String
    indexError?: string | null; // String
    indexStatus: string; // String!
    jobId: string; // String!
    userId: string; // String!
  }
  GuestAuthPayload: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  MediaConfig: { // root type
    nuggetOfTheDayImageUrl?: string | null; // String
    nuggetOfTheDayTrackedDownloadUrl?: string | null; // String
    thumbnailBaseUrlNoCDN: string; // String!
  }
  Mutation: {};
  NuggetOfTheDay: { // root type
    author?: string | null; // String
    body?: string | null; // String
    bookId?: string | null; // String
    isLiked?: boolean | null; // Boolean
    quoteId?: string | null; // String
    title?: string | null; // String
    userId?: string | null; // String
  }
  Query: {};
  Quote: { // root type
    _id: string; // String!
    bookId: string; // String!
    liked?: boolean | null; // Boolean
    quote?: string | null; // String
  }
  RefreshTokenResponse: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  Subscription: { // root type
    _id: string; // String!
    active: boolean; // Boolean!
    bookIds?: string[] | null; // [String!]
    endTime: string; // String!
    frequency: number; // Int!
    jobIds?: string[] | null; // [String!]
    startTime: string; // String!
    userId: string; // String!
  }
  User: { // root type
    _id: string; // String!
    email?: string | null; // String
    firstName?: string | null; // String
    isGuest?: boolean | null; // Boolean
    lastName?: string | null; // String
    nickName?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
    subscription: NexusGenRootTypes['Subscription']; // Subscription!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // field return type
    _id: string; // String!
    contextObjectKey: string | null; // String
    indexError: string | null; // String
    indexStatus: string | null; // String
    isSubscribed: boolean | null; // Boolean
    jobId: string; // String!
    title: string; // String!
    userId: string; // String!
  }
  BookIndexStatus: { // field return type
    contextObjectKey: string | null; // String
    indexError: string | null; // String
    indexStatus: string; // String!
    jobId: string; // String!
    userId: string; // String!
  }
  GuestAuthPayload: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  MediaConfig: { // field return type
    nuggetOfTheDayImageUrl: string | null; // String
    nuggetOfTheDayTrackedDownloadUrl: string | null; // String
    thumbnailBaseUrlNoCDN: string; // String!
  }
  Mutation: { // field return type
    addBookToSubscriptions: boolean; // Boolean!
    addQuote: boolean; // Boolean!
    clearSubscriptions: boolean; // Boolean!
    createSubscriptions: boolean; // Boolean!
    deleteBook: boolean; // Boolean!
    likeQuote: boolean; // Boolean!
    loginWithApple: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
    refreshTokens: NexusGenRootTypes['RefreshTokenResponse'] | null; // RefreshTokenResponse
    registerGuest: NexusGenRootTypes['GuestAuthPayload'] | null; // GuestAuthPayload
    removeBookFromSubscriptions: boolean; // Boolean!
    rescheduleBookSubscriptions: boolean; // Boolean!
    retryCloudIndex: NexusGenRootTypes['BookIndexStatus']; // BookIndexStatus!
    sendQuoteNotification: boolean; // Boolean!
    turnOffBookSubscriptions: boolean; // Boolean!
    turnOnBookSubscriptions: boolean; // Boolean!
    unlikeQuote: boolean; // Boolean!
    updateUserDeviceToken: boolean | null; // Boolean
    updateUserNickname: NexusGenRootTypes['User'] | null; // User
  }
  NuggetOfTheDay: { // field return type
    author: string | null; // String
    body: string | null; // String
    bookId: string | null; // String
    isLiked: boolean | null; // Boolean
    quoteId: string | null; // String
    title: string | null; // String
    userId: string | null; // String
  }
  Query: { // field return type
    getBookIndexStatuses: NexusGenRootTypes['BookIndexStatus'][]; // [BookIndexStatus!]!
    getBookInfo: NexusGenRootTypes['Book']; // Book!
    getLikedQuotesForBook: NexusGenRootTypes['Quote'][]; // [Quote!]!
    getMediaConfig: NexusGenRootTypes['MediaConfig'] | null; // MediaConfig
    getNuggetOfTheDay: NexusGenRootTypes['NuggetOfTheDay'] | null; // NuggetOfTheDay
    getQuotesForBook: NexusGenRootTypes['Quote'][]; // [Quote!]!
    getRandomPhoto: boolean; // Boolean!
    getUser: NexusGenRootTypes['User']; // User!
    getUserBooks: NexusGenRootTypes['Book'][]; // [Book!]!
    getUserLikedQuotes: NexusGenRootTypes['Quote'][]; // [Quote!]!
    getUserSubscriptions: Array<NexusGenRootTypes['Subscription'] | null>; // [Subscription]!
    getViewedQuotesForBook: NexusGenRootTypes['Quote'][]; // [Quote!]!
    searchBooks: NexusGenRootTypes['Book'][]; // [Book!]!
    searchQuotes: NexusGenRootTypes['Quote'][]; // [Quote!]!
    searchUserLikedQuotes: NexusGenRootTypes['Quote'][]; // [Quote!]!
    whoAmI: NexusGenRootTypes['User'] | null; // User
  }
  Quote: { // field return type
    _id: string; // String!
    book: NexusGenRootTypes['Book'] | null; // Book
    bookId: string; // String!
    liked: boolean | null; // Boolean
    quote: string | null; // String
  }
  RefreshTokenResponse: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  Subscription: { // field return type
    _id: string; // String!
    active: boolean; // Boolean!
    bookIds: string[] | null; // [String!]
    endTime: string; // String!
    frequency: number; // Int!
    getBookProgress: NexusGenRootTypes['Book'] | null; // Book
    jobIds: string[] | null; // [String!]
    myBookIndexStatuses: NexusGenRootTypes['BookIndexStatus'] | null; // BookIndexStatus
    startTime: string; // String!
    userId: string; // String!
  }
  User: { // field return type
    _id: string; // String!
    email: string | null; // String
    firstName: string | null; // String
    isGuest: boolean | null; // Boolean
    lastName: string | null; // String
    nickName: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
    subscription: 'Subscription'
    user: 'User'
  }
  Book: { // field return type name
    _id: 'String'
    contextObjectKey: 'String'
    indexError: 'String'
    indexStatus: 'String'
    isSubscribed: 'Boolean'
    jobId: 'String'
    title: 'String'
    userId: 'String'
  }
  BookIndexStatus: { // field return type name
    contextObjectKey: 'String'
    indexError: 'String'
    indexStatus: 'String'
    jobId: 'String'
    userId: 'String'
  }
  GuestAuthPayload: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
    user: 'User'
  }
  MediaConfig: { // field return type name
    nuggetOfTheDayImageUrl: 'String'
    nuggetOfTheDayTrackedDownloadUrl: 'String'
    thumbnailBaseUrlNoCDN: 'String'
  }
  Mutation: { // field return type name
    addBookToSubscriptions: 'Boolean'
    addQuote: 'Boolean'
    clearSubscriptions: 'Boolean'
    createSubscriptions: 'Boolean'
    deleteBook: 'Boolean'
    likeQuote: 'Boolean'
    loginWithApple: 'AuthPayload'
    refreshTokens: 'RefreshTokenResponse'
    registerGuest: 'GuestAuthPayload'
    removeBookFromSubscriptions: 'Boolean'
    rescheduleBookSubscriptions: 'Boolean'
    retryCloudIndex: 'BookIndexStatus'
    sendQuoteNotification: 'Boolean'
    turnOffBookSubscriptions: 'Boolean'
    turnOnBookSubscriptions: 'Boolean'
    unlikeQuote: 'Boolean'
    updateUserDeviceToken: 'Boolean'
    updateUserNickname: 'User'
  }
  NuggetOfTheDay: { // field return type name
    author: 'String'
    body: 'String'
    bookId: 'String'
    isLiked: 'Boolean'
    quoteId: 'String'
    title: 'String'
    userId: 'String'
  }
  Query: { // field return type name
    getBookIndexStatuses: 'BookIndexStatus'
    getBookInfo: 'Book'
    getLikedQuotesForBook: 'Quote'
    getMediaConfig: 'MediaConfig'
    getNuggetOfTheDay: 'NuggetOfTheDay'
    getQuotesForBook: 'Quote'
    getRandomPhoto: 'Boolean'
    getUser: 'User'
    getUserBooks: 'Book'
    getUserLikedQuotes: 'Quote'
    getUserSubscriptions: 'Subscription'
    getViewedQuotesForBook: 'Quote'
    searchBooks: 'Book'
    searchQuotes: 'Quote'
    searchUserLikedQuotes: 'Quote'
    whoAmI: 'User'
  }
  Quote: { // field return type name
    _id: 'String'
    book: 'Book'
    bookId: 'String'
    liked: 'Boolean'
    quote: 'String'
  }
  RefreshTokenResponse: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
  }
  Subscription: { // field return type name
    _id: 'String'
    active: 'Boolean'
    bookIds: 'String'
    endTime: 'String'
    frequency: 'Int'
    getBookProgress: 'Book'
    jobIds: 'String'
    myBookIndexStatuses: 'BookIndexStatus'
    startTime: 'String'
    userId: 'String'
  }
  User: { // field return type name
    _id: 'String'
    email: 'String'
    firstName: 'String'
    isGuest: 'Boolean'
    lastName: 'String'
    nickName: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addBookToSubscriptions: { // args
      bookId: string; // String!
    }
    addQuote: { // args
      bookId: string; // String!
      quote: string; // String!
    }
    clearSubscriptions: { // args
      userId: string; // String!
    }
    createSubscriptions: { // args
      bookIds: string[]; // [String!]!
      userId: string; // String!
    }
    deleteBook: { // args
      bookId: string; // String!
    }
    likeQuote: { // args
      quoteId: string; // String!
    }
    loginWithApple: { // args
      firstName?: string | null; // String
      idToken: string; // String!
      lastName?: string | null; // String
      timeZone?: string | null; // String
    }
    refreshTokens: { // args
      refreshToken: string; // String!
    }
    registerGuest: { // args
      guestId: string; // String!
    }
    removeBookFromSubscriptions: { // args
      bookId: string; // String!
    }
    rescheduleBookSubscriptions: { // args
      endTime: string; // String!
      frequency: number; // Int!
      startTime: string; // String!
    }
    retryCloudIndex: { // args
      jobId: string; // String!
    }
    sendQuoteNotification: { // args
      bookId: string; // String!
      syncToNuggetOfTheDay: boolean; // Boolean!
      userId: string; // String!
    }
    unlikeQuote: { // args
      quoteId: string; // String!
    }
    updateUserDeviceToken: { // args
      token?: string | null; // String
    }
    updateUserNickname: { // args
      nickname: string; // String!
    }
  }
  Query: {
    getBookIndexStatuses: { // args
      jobIds: string[]; // [String!]!
    }
    getBookInfo: { // args
      bookId: string; // String!
    }
    getLikedQuotesForBook: { // args
      bookId: string; // String!
      limit: number; // Int!
      offset: number; // Int!
    }
    getQuotesForBook: { // args
      bookId: string; // String!
      limit: number; // Int!
      offset: number; // Int!
    }
    getRandomPhoto: { // args
      orientation?: string | null; // String
      query?: string | null; // String
    }
    getUser: { // args
      userId: string; // String!
    }
    getUserBooks: { // args
      limit?: number | null; // Int
      offset?: number | null; // Int
    }
    getUserLikedQuotes: { // args
      limit: number; // Int!
      offset: number; // Int!
    }
    getViewedQuotesForBook: { // args
      bookId: string; // String!
      userId: string; // String!
    }
    searchBooks: { // args
      limit?: number | null; // Int
      offset?: number | null; // Int
      searchText: string; // String!
    }
    searchQuotes: { // args
      limit: number; // Int!
      offset: number; // Int!
      searchString: string; // String!
    }
    searchUserLikedQuotes: { // args
      limit: number; // Int!
      offset: number; // Int!
      searchString: string; // String!
    }
  }
  Subscription: {
    getBookProgress: { // args
      jobId?: string | null; // String
      userId?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}